{% set name = "iscd-commons" %}
{% set version = "1.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  # there are no tagged releases which so using archives of specific commits
  url: https://github.com/ISCDtoolbox/Commons/archive/refs/tags/v{{ version }}.zip
  sha256: 2d6e4f02852146609efbb9288b70ca5b6763e6b2ac61fffc64ebd303a3577896

build:
  number: 0
  skip: true  # [py<3 or win] # Cannot open include file: 'pthread.h': No such file or directory
  ignore_run_exports_from:
    - {{ compiler('cxx') }}
  run_exports:
    - {{ pin_subpackage('iscd-commons', max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - cmake
    - make  # [not win]
    - jom  # [win]

test:
  commands:
    - test -f $PREFIX/lib/libCommons.so  # [linux]
    - test -f $PREFIX/lib/libCommons.dylib  # [osx]
    - test -f $PREFIX/include/chrono.h
    - test -f $PREFIX/include/eigen.h
    - test -f $PREFIX/include/libmesh5.h        
    - test -f $PREFIX/include/lplib3.h
    - test -f $PREFIX/include/sparse.h      

about:
  home: https://iscd.sorbonne-universite.fr/
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: 'ISCD - Commons library'
  description: |
    Common codes used for ISCD softwares (Linear algebra, Chrono, I/O...)
  doc_url: https://github.com/ISCDtoolbox/Commons/blob/master/README.md
  dev_url: https://github.com/ISCDtoolbox/Commons 

extra:
  recipe-maintainers:
    - ldallolio
    - fbordeu
